### ISSUE TITLE
Issue with cups_queue could not autoload puppet/type/cups_queue

### ISSUE THREAD

**Issue by DavidHromyk** [leoarnold/puppet-cups#104] opened 2019-02-11 22:54 UTC
**Given** SmartOS x86_64 with Puppet v5 and CUPS 1.5.

**When** I apply the manifest

```puppet

class cups_print_server
{
  
  include cups

  cups_queue { 'MinimalRaw':
    ensure => 'printer',
    uri    => 'lpd://192.168.2.105/binary_p1'
  }
}
```

**In order to** Create a print queue

**Then** I get the error message:

```Shell
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/cups_queue: /home/david.hromyk/.puppetlabs/etc/code/environments/internal/modules/cups/lib/puppet/type/cups_queue.rb:104: unknown type of %string
      return "created a #{should_to_s(new_value)}" unless %i[class printer].include?(current_value)
                                                            ^ (file: /home/david.hromyk/.puppetlabs/etc/code/environments/internal/modules/cups_print_server/manifests/init.pp, line: 6, column: 3) on node ops-b3-print02.lrscorp.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by DavidHromyk** [comment] 2019-02-11 22:57
FWIW I used a SmartOS override in my params.pp file.

**Comment by leoarnold** [comment] 2019-02-12 17:25
Using this repository's `HEAD` is not advised. Either pin a tag or use a packaged version from the forge. Duplicate of #91.

**Closed** 2019-02-12 17:25 UTC
